/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vnERO7bRqdw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  DialogTrigger,
  DialogTitle,
  DialogDescription,
  DialogHeader,
  DialogContent,
  Dialog,
} from "@/components/ui/dialog";
import AddTask from "./AddTask";
import EditTask from "./EditTask";

export default function dialog({
  children,
  title,
  task_content,
  adding,
  editing,
}: {
  children: React.ReactNode;
  title: string;
  task_content: string;
  task_placeholder: string;
  adding?: boolean;
  editing?: boolean;
}) {
  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="text-center">{title}</DialogTitle>
          <DialogDescription className="text-center">
            {task_content}
          </DialogDescription>
        </DialogHeader>
        { adding && <AddTask />}
        { editing && <EditTask />}
      </DialogContent>
    </Dialog>
  );
}
